# Soring, searching, and counting

In [2]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

In [4]:
author = 'kyubyong. longinglove@nate.com'

## Sorting

Q1. Sort x along the second axis.

In [5]:
x = np.array([[1,4],[3,1]])

x.sort(axis=1)
x

array([[1, 4],
       [1, 3]])

Q2. Sort pairs of surnames and first names and return their indices. (first by surname, then by name).

In [6]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')

x = np.lexsort((first_names, surnames))

x

array([1, 2, 0], dtype=int64)

Q3. Get the indices that would sort x along the second axis.

In [7]:
x = np.array([[1,4],[3,1]])

x.argsort(axis=1)

array([[0, 1],
       [1, 0]], dtype=int64)

Q4. Create an array such that its fifth element would be the same as the element of sorted x, and it divide other elements by their value.

In [10]:
x = np.random.permutation(10)
print("x =", x)

y = np.partition(x, 5)
y

x = [4 2 9 6 0 7 1 5 3 8]


array([2, 0, 3, 1, 4, 5, 6, 7, 9, 8])

Q5. Create the indices of an array such that its third element would be the same as the element of sorted x, and it divide other elements by their value.

In [18]:
x = np.random.permutation(10)
print("x =", x)

print(np.partition(x, 3))
y = np.argpartition(x, 3)
y

x = [8 9 4 6 0 5 1 7 2 3]
[1 0 2 3 9 5 6 7 4 8]


array([6, 4, 8, 9, 1, 5, 3, 7, 2, 0], dtype=int64)

## Searching

Q6. Get the maximum and minimum values and their indices of x along the second axis.

In [21]:
x = np.random.permutation(10).reshape(2, 5)
print("x =", x)

x.max(axis=1), x.min(axis=1)

x = [[3 9 6 5 7]
 [4 2 1 8 0]]


(array([9, 8]), array([3, 0]))

Q7. Get the maximum and minimum values and their indices of x along the second axis, ignoring NaNs.

In [22]:
x = np.array([[np.nan, 4], [3, 2]])
np.nanmax(x, axis=1), np.nanmin(x, axis=1)


(array([4., 3.]), array([4., 2.]))

Q8. Get the values and indices of the elements that are bigger than 2 in x.


In [23]:
x = np.array([[1, 2, 3], [1, 3, 5]])

x[x>2]

array([3, 3, 5])

Q9. Get the indices of the elements that are bigger than 2 in the flattend x.

In [25]:
x = np.array([[1, 2, 3], [1, 3, 5]])

x.flatten()[x.flatten()>2]

array([3, 3, 5])

Q10. Check the elements of x and return 0 if it is less than 0, otherwise the element itself.

In [26]:
x = np.arange(-5, 4).reshape(3, 3)

x[x<0] = 0
x

array([[0, 0, 0],
       [0, 0, 0],
       [1, 2, 3]])

Q11. Get the indices where elements of y should be inserted to x to maintain order.

In [29]:
x = [1, 3, 5, 7, 9]
y = [0, 4, 2, 6]

np.searchsorted(x, y)

array([0, 2, 1, 3], dtype=int64)

## Counting

Q12. Get the number of nonzero elements in x.

In [30]:
x = [[0,1,7,0,0],[3,0,0,2,19]]

np.nonzero(x)

(array([0, 0, 1, 1, 1], dtype=int64), array([1, 2, 0, 3, 4], dtype=int64))