# Array creation routines

## Ones and zeros

In [1]:
import numpy as np

Create a new array of 2*2 integers, without initializing entries.

In [10]:
np.zeros((2, 2), int)

array([[0, 0],
       [0, 0]])

Let X = np.array([1,2,3], [4,5,6], np.int32). 
Create a new array with the same shape and type as X.

In [19]:
X = np.array([[1,2,3], [4,5,6]], np.int32)

# Y = np.empty_like(X)
Y = np.empty(X.shape, X.dtype)
Y

array([[1, 2, 3],
       [4, 5, 6]])

Create a 3-D array with ones on the diagonal and zeros elsewhere.

In [27]:
# np.eye(3, dtype=int)
# np.identity(3, dtype=int)
np.ones((3, 3), int) * np.diag(np.ones(3, int))


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

Create a new array of 3*2 float numbers, filled with ones.

In [30]:
np.ones((3, 2), dtype=np.float32)

array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [33]:
x = np.arange(4, dtype=np.int64)

np.ones_like(x)


array([1, 1, 1, 1], dtype=int64)

Create a new array of 3*2 float numbers, filled with zeros.

In [34]:
np.zeros((3, 2), dtype=)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

Let x = np.arange(4, dtype=np.int64). Create an array of zeros with the same shape and type as X.

In [36]:
x = np.arange(4, dtype=np.int64)

np.zeros_like(x)


array([0, 0, 0, 0], dtype=int64)

Create a new array of 2*5 uints, filled with 6.

In [38]:
np.full((2, 5), 6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

Let x = np.arange(4, dtype=np.int64). Create an array of 6's with the same shape and type as X.

In [39]:
x = np.arange(4, dtype=np.int64)

np.full_like(x, 6)

array([6, 6, 6, 6], dtype=int64)

## From existing data

Create an array of [1, 2, 3].

In [41]:
np.array([1, 2, 3])

array([1, 2, 3])

Let x = [1, 2]. Convert it into an array.

In [42]:
x = [1,2]

np.array(x)

array([1, 2])

Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [47]:
X = np.array([[1, 2], [3, 4]])

np.asmatrix(X)

matrix([[1, 2],
        [3, 4]])

Let x = [1, 2]. Conver it into an array of `float`.

In [48]:
x = [1, 2]

np.asarray(x, np.float32)

array([1., 2.], dtype=float32)

Let x = np.array([30]). Convert it into scalar of its single element, i.e. 30.

In [56]:
x = np.array([30])

x.item()

30

Let x = np.array([1, 2, 3]). Create a array copy of x, which has a different id from x.

In [62]:
x = np.array([1, 2, 3])

x_copy = x.copy()

print(id(x), x)
print(id(x_copy), x_copy)

1635476223536 [1 2 3]
1635475809424 [1 2 3]


## Numerical ranges

Create an array of 2, 4, 6, 8, ..., 100.

In [65]:
np.arange(0, 101, 2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [86]:
np.linspace(3, 10, 50, dtype=np.float32)

# arr = []
# i = 3
# while i < 10:
#     arr.append(i)
#     i += float((10 - 3) / 50)

# np.array(arr, dtype=np.float32)


array([ 3.       ,  3.142857 ,  3.2857144,  3.4285715,  3.5714285,
        3.7142856,  3.857143 ,  4.       ,  4.142857 ,  4.285714 ,
        4.428571 ,  4.571429 ,  4.714286 ,  4.857143 ,  5.       ,
        5.142857 ,  5.285714 ,  5.428571 ,  5.571429 ,  5.714286 ,
        5.857143 ,  6.       ,  6.142857 ,  6.285714 ,  6.428571 ,
        6.571429 ,  6.714286 ,  6.857143 ,  7.       ,  7.142857 ,
        7.285714 ,  7.428571 ,  7.571429 ,  7.714286 ,  7.857143 ,
        8.       ,  8.142858 ,  8.285714 ,  8.428572 ,  8.571428 ,
        8.714286 ,  8.857142 ,  9.       ,  9.142858 ,  9.285714 ,
        9.428572 ,  9.571428 ,  9.714286 ,  9.857142 , 10.       ],
      dtype=float32)

Create a 1-D array of 50 element spaced evenly on a log scale between 3. and 10., exclusive.

In [78]:
np.logspace(3, 10, 50, dtype=np.float32, endpoint=False)

array([1.00000000e+03, 1.38038428e+03, 1.90546069e+03, 2.63026807e+03,
       3.63078052e+03, 5.01187256e+03, 6.91830957e+03, 9.54992578e+03,
       1.31825674e+04, 1.81970078e+04, 2.51188652e+04, 3.46736836e+04,
       4.78630078e+04, 6.60693438e+04, 9.12010859e+04, 1.25892539e+05,
       1.73780078e+05, 2.39883297e+05, 3.31131125e+05, 4.57088188e+05,
       6.30957375e+05, 8.70963562e+05, 1.20226438e+06, 1.65958688e+06,
       2.29086775e+06, 3.16227775e+06, 4.36515850e+06, 6.02559600e+06,
       8.31763750e+06, 1.14815360e+07, 1.58489320e+07, 2.18776160e+07,
       3.01995180e+07, 4.16869400e+07, 5.75439920e+07, 7.94328240e+07,
       1.09647816e+08, 1.51356128e+08, 2.08929616e+08, 2.88403136e+08,
       3.98107168e+08, 5.49540864e+08, 7.58577600e+08, 1.04712858e+09,
       1.44543974e+09, 1.99526234e+09, 2.75422874e+09, 3.80189389e+09,
       5.24807475e+09, 7.24435968e+09], dtype=float32)

## Building matrices

Let X = np.array([[ 0,  1,  2,  3],
                  [ 4,  5,  6,  7],
                 [ 8,  9, 10, 11]]).
                 Get the diagonal of X, that is, [0, 5, 10].

In [74]:
X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])
np.diag(np.asmatrix(X))

array([ 0,  5, 10])

Create a 2-D array whose diagonal equals [1, 2, 3, 4] and 0's elsewhere.

In [75]:
np.array(np.diag([1, 2, 3, 4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

Create an array which looks like below.
array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.]])

In [115]:
np.tri(3, 5, -1, dtype=float)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

Create an array which looks like below.
array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

In [124]:
# np.arange(1, 13, dtype=float)

np.arange(1, 13, dtype=float).reshape(4, 3) * np.tri(4, 3, -1, dtype=float)

array([[ 0.,  0.,  0.],
       [ 4.,  0.,  0.],
       [ 7.,  8.,  0.],
       [10., 11., 12.]])

Create an array which looks like below. array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

In [127]:
np.triu(np.arange(1, 13, dtype=float).reshape(4, 3), -1)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 0.,  8.,  9.],
       [ 0.,  0., 12.]])